import type { ContentProvider, ProductResource, Resource } from './types';
import { DEFAULT_MAX_CONTENT_WORDS } from './constants';
import { BotRulesEngine } from './bot-rules';

// ── Helpers (exported for testing) ──────────────────────────────────

/** Strip all HTML tags from a string. */
export function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, '').trim();
}

/** Trim text to a maximum number of words, adding "..." if truncated. */
export function trimWords(text: string, maxWords: number): string {
  const words = text.split(/\s+/).filter(Boolean);
  if (words.length <= maxWords) return words.join(' ');
  return words.slice(0, maxWords).join(' ') + '...';
}

/** Get price range string from product variants. */
export function getPriceRange(variants: ProductResource['variants']): string {
  if (!variants || variants.length === 0) return '';
  const prices = variants.map((v) => parseFloat(v.price)).filter((p) => !isNaN(p));
  if (prices.length === 0) return '';

  let min = prices[0];
  let max = prices[0];
  for (let i = 1; i < prices.length; i++) {
    if (prices[i] < min) min = prices[i];
    if (prices[i] > max) max = prices[i];
  }

  if (min === max) return min.toFixed(2);
  return `${min.toFixed(2)} – ${max.toFixed(2)}`;
}

/** Get sale info from price and compareAtPrice. */
export function getSalePrices(price?: string, compareAtPrice?: string): string | null {
  if (!compareAtPrice || !price) return null;
  const priceNum = parseFloat(price);
  const compareNum = parseFloat(compareAtPrice);
  if (isNaN(priceNum) || isNaN(compareNum)) return null;
  if (compareNum > priceNum) {
    return `Sale: ${price} (was ${compareAtPrice})`;
  }
  return null;
}

/** Get availability status from a ProductResource. */
export function getAvailabilityStatus(resource: ProductResource): string {
  if (resource.available === false) return 'Out of Stock';
  return 'In Stock';
}

// ── LlmsGenerator ───────────────────────────────────────────────────

export class LlmsGenerator {
  constructor(
    private provider: ContentProvider,
    private config: {
      siteName: string;
      siteUrl: string;
      siteDescription?: string;
      botRules: BotRulesEngine;
      maxContentWords?: number;
    },
  ) {}

  async generate(isFull: boolean, locale?: string): Promise<string> {
    const { siteName, siteUrl, siteDescription, botRules } = this.config;
    const maxWords = this.config.maxContentWords ?? DEFAULT_MAX_CONTENT_WORDS;
    const url = siteUrl.replace(/\/$/, '');
    const output: string[] = [];

    // ── Header ───────────────────────────────────────────────────────
    output.push(`# ${siteName}`);
    output.push('');

    if (siteDescription) {
      output.push(`> ${siteDescription}`);
      output.push('');
    }

    // ── Metadata ─────────────────────────────────────────────────────
    output.push(`- URL: ${url}`);
    output.push(`- llms.txt: ${url}/llms.txt`);
    output.push(`- llms-full.txt: ${url}/llms-full.txt`);

    if (locale) {
      output.push(`- Language: ${locale}`);
    }

    output.push('');

    // ── AI Crawler Rules ─────────────────────────────────────────────
    output.push('## AI Crawler Rules');
    output.push('');

    for (const line of botRules.getCrawlerStatusLines()) {
      output.push(line);
    }

    output.push('');

    // ── Resource Sections ────────────────────────────────────────────
    const sections = await this.provider.getSections(locale ? { locale } : undefined);

    for (const section of sections) {
      const resources = section.resources.filter((r) => !r.excluded);
      if (resources.length === 0) continue;

      output.push(`## ${section.name}`);
      output.push('');

      for (const resource of resources) {
        // Standard line: - [title](url): description [keywords]
        let line = `- [${resource.title}](${resource.url})`;

        if (resource.description) {
          line += `: ${resource.description}`;
        }

        if (resource.keywords) {
          line += ` [${resource.keywords}]`;
        }

        output.push(line);

        // Full format: extra details
        if (isFull) {
          if (section.type === 'product') {
            this.appendProductDetails(output, resource as ProductResource, maxWords);
          } else {
            // Non-product: just content
            if (resource.content) {
              const content = stripHtml(resource.content);
              if (content) {
                output.push(`  ${trimWords(content, maxWords)}`);
              }
            }
          }

          output.push('');
        }
      }

      output.push('');
    }

    // ── Footer ───────────────────────────────────────────────────────
    output.push('---');
    output.push('Generated by GEO AI Core');
    output.push(
      `Last updated: ${new Date().toISOString().replace('T', ' ').slice(0, 16)} UTC`,
    );

    return output.join('\n');
  }

  private appendProductDetails(
    output: string[],
    resource: ProductResource,
    maxWords: number,
  ): void {
    // Content
    if (resource.content) {
      const content = stripHtml(resource.content);
      if (content) {
        output.push(`  ${trimWords(content, maxWords)}`);
      }
    }

    // Price
    if (resource.variants && resource.variants.length > 0) {
      const priceRange = getPriceRange(resource.variants);
      if (priceRange) {
        const currency = resource.currency ? ` ${resource.currency}` : '';
        output.push(`  Price: ${priceRange}${currency}`);
      }
    } else if (resource.price) {
      const currency = resource.currency ? ` ${resource.currency}` : '';
      output.push(`  Price: ${resource.price}${currency}`);
    }

    // Sale
    const sale = getSalePrices(resource.price, resource.compareAtPrice);
    if (sale) {
      output.push(`  ${sale}`);
    }

    // Availability
    output.push(`  Availability: ${getAvailabilityStatus(resource)}`);

    // Variants
    if (resource.variants && resource.variants.length > 1) {
      const titles = resource.variants.map((v) => v.title).join(', ');
      output.push(`  Variants: ${titles}`);
    }
  }
}
